service: shops

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-2
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  create:
    handler: create.create
    events:
      - http:
          path: shops
          method: post
          cors: true

  list:
    handler: list.list
    events:
      - http:
          path: shops
          method: get
          cors: true

  get:
    handler: get.get
    events:
      - http:
          path: shops/{id}
          method: get
          cors: true

  update:
    handler: update.update
    events:
      - http:
          path: shops/{id}
          method: put
          cors: true

  delete:
    handler: delete.delete
    events:
      - http:
          path: shops/{id}
          method: delete
          cors: true

#  getAllProducts:
#    handler: getAllProducts.get
#    events:
#      - http:
#          path: shops/{id}/products
#          method: get
#          cors: true

resources:
  Resources:
    shopsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
