version: '2'
services:
  node-app:
    build: app
    ports:
      - "4000:8080"
    volumes:
      - ./app/src:/myapp/src
    depends_on:
      - db
      - mongodb
    environment:
      - PG_HOST=db
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_DATABASE=app
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - PUBLIC_APP_PORT=4000
      - DB_TYPE=postgres

  db:
    build: db

  mongodb:
    image: "mongo:latest"
